services:

  api:
    build:
      context: .
      dockerfile: ./api/dockerfile
    container_name: Macuin_API
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:12345@postgres:5432/DB_macuin

  postgres:
    image: postgres:15
    container_name: MacuinSQL
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: DB_macuin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DB_macuin"]
      interval: 5s
      retries: 5
      timeout: 5s

  laravel_front:
    build: ./laravel
    container_name: Macuin_Laravel
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - api

  flask_front:
    build: ./flask
    container_name: Macuin_Flask
    ports:
      - "5001:5001"
    volumes:
      - ./flask:/app
    depends_on:
      - api

volumes:
  postgres_data:
