FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY ./api/requirements.txt /app/api/
RUN pip install --no-cache-dir -r /app/api/requirements.txt

# The application is executed by mapping the volume and running uvicorn on the api package
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "5000"]
